# Generated by Django 4.1.7 on 2023-03-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
