# Generated by Django 4.1.7 on 2023-03-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipkart',
            name='is_ordered',
        ),
    ]
